# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-slim

# Set a working directory
WORKDIR /app

# Copy all files to the container
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir google-api-python-client mcp[cli] python-dotenv youtube-transcript-api

# Set environment variables placeholders (they will be overridden by startCommand config)
ENV YOUTUBE_API_KEY=your_youtube_api_key

# Command to run the MCP server
CMD ["python", "server.py"]
